### ISSUE TITLE
Beethoven Sprint Planning

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#214]
Enhancements plone.restapi:

- [ ] User registration https://github.com/plone/plone.restapi/issues/215
- [x] Tagged values support https://github.com/plone/plone.restapi/issues/213
- [x] Vocabularies endpoint https://github.com/plone/plone.restapi/issues/212
- [x] Choices @types endpoint https://github.com/plone/plone.restapi/issues/199
- [x] Mode attribute @types endpoint https://github.com/plone/plone.restapi/issues/198
- [x] Addable types constraint https://github.com/plone/plone.restapi/issues/173
- [x] Copy/Pages https://github.com/plone/plone.restapi/issues/180
- [x] Sharing https://github.com/plone/plone.restapi/issues/175 *
- [x] Permissions https://github.com/plone/plone.restapi/issues/169
- [x] Field order @types endpoint https://github.com/plone/plone.restapi/issues/108
- [x] Widget field @types endpoint https://github.com/plone/plone.restapi/issues/104
- [ ] File upload enhancements https://github.com/plone/plone.restapi/issues/197
- [ ] Custom user properties https://github.com/plone/plone.restapi/issues/211
- [ ] Multilingual endpoint https://github.com/plone/plone.restapi/issues/225

Questions / API Design:

- [ ] Framing https://github.com/plone/plone.restapi/issues/149 *
- [ ] Multi segment routes https://github.com/plone/plone.restapi/issues/222
- [ ] ZCML permissions https://github.com/plone/plone.restapi/issues/221
- [ ] JSON Schema <-> Plone Behavior https://github.com/plone/plone.restapi/issues/218 *
- [ ] Generic setup endpoint https://github.com/plone/plone.restapi/issues/217
- [x] Naming conventions URL attributes https://github.com/plone/plone.restapi/issues/194
- [ ] Components concept https://github.com/plone/plone.restapi/issues/193
- [ ] plone.restapi demo https://github.com/plone/plone.restapi/issues/188
- [ ] Null values https://github.com/plone/plone.restapi/issues/187
- [ ] Redirects https://github.com/plone/plone.restapi/issues/181
- [ ] Currently auth user https://github.com/plone/plone.restapi/issues/179
- [ ] Dual auth https://github.com/plone/plone.restapi/issues/178
- [ ] Decouple testing https://github.com/plone/plone.restapi/issues/162
- [ ] Browsable API https://github.com/plone/plone.restapi/issues/161
- [ ] plone.restapi / plone server sync https://github.com/plone/plone.restapi/issues/157 *
- [ ] plone protect https://github.com/plone/plone.restapi/issues/155
- [ ] username vs login https://github.com/plone/plone.restapi/issues/154
- [ ] Schema in content response https://github.com/plone/plone.restapi/issues/136
- [ ] User name vs id https://github.com/plone/plone.restapi/issues/125
- [ ] Evaluate TUS https://github.com/plone/plone.restapi/issues/79 *

Plone Server:

- [ ] todo Ramon

Bugs:

- [ ] Search endpoint VHM https://github.com/plone/plone.restapi/issues/186
- [x] Wrong @id on create folder https://github.com/plone/plone.restapi/issues/176

Documentation / Testing:

- [x] HTTP calls in docs https://github.com/plone/plone.restapi/issues/196
- [ ] Swagger spec/docs https://github.com/plone/plone.restapi/issues/189
- [ ] Docs for POST wrong https://github.com/plone/plone.restapi/issues/174
- [x] Test coverage below 100 % https://github.com/plone/plone.restapi/issues/33

SDKs / Examples:

- [x] React examples https://github.com/plone/plone.restapi/issues/202
- [ ] POSTPONED: React SDK https://github.com/plone/plone.restapi/issues/201
- [x] Angular SDK https://github.com/plone/plone.restapi/issues/200

Roadmap:

- [ ] PLIP: Ship Plone with plone.rest (5.x?)
- [ ] plone.restapi 1.0 (feature complete, framing, hypermedia, actions)
- [ ] PLIP: Ship Plone with plone.restapi (5.x, 6.0?)
- [ ] Angular 2 Library/SDK
- [ ] Browsable API

Future / Discussion:

- [ ] "Headless CMS" definition, competitors, market, etc.
- [ ] Where do we want Plone to be in 1,2,5 years? How do we get there?
- [ ] Current status of JavaScript in Plone (mockup, patterns, requirejs)
- [ ] Status ReactJS (Nathan)
- [ ] Status Webpack (Asko)
- [ ] How can we integrate the latest JS technology into Plone core?
- [ ] GSoC (Angular 2, React, Browsable API, PloneFormGen) https://github.com/plone/plone.restapi/issues/236

**Comment by ebrehault** [comment]
@tisto in Questions/API design, maybe we shall discuss if we want endpoint(s) to manage configuration (like importing a kind of JSON-based GS profile).

**Comment by tisto** [comment]
@ebrehault good point: https://github.com/plone/plone.restapi/issues/217

**Comment by tisto** [comment]
@bloodbare FYI: I marked all issues we just discussed in our call with *.

**Comment by acsr** [comment]
Fixed wrong ticket id in Swagger topic
