### ISSUE TITLE
[WIP] Roadmap to plone.restapi 1.0

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#274]
The Plone Beethoven Sprint in Bonn was a major success! We finished far more than what we expected and I think we can plan for a final plone.restapi 1.0 release:

**plone.restapi 1.0a10**

- [x] Incorrect Json examples in plone restapi documentation: https://github.com/plone/plone.restapi/issues/273
- [x] 1.0a10 Release: https://github.com/plone/plone.restapi/issues/266

Planned: March 2017

**plone.restapi 1.0a13**

- [x] Layout Support: https://github.com/plone/plone.restapi/pull/313

**plone.restapi 1.0a14**

- [x] History Endpoint: https://github.com/plone/plone.restapi/pull/306

**plone.restapi 1.0a15**

- [x] Deprecation Policy: https://github.com/plone/plone.restapi/issues/317
- [x] Deprecate Components: https://github.com/plone/plone.restapi/pull/312
- [x] Control Panels: https://github.com/plone/plone.restapi/issues/342 https://github.com/plone/plone.restapi/pull/339

Planned: May 2017

**plone.restapi 1.0a16**

- [x] TUS-Upload: https://github.com/plone/plone.restapi/pull/261
- [x] Expansion (was: Framing Proposal): https://github.com/plone/plone.restapi/issues/149
- [x] Plone 5.1 support: https://github.com/plone/plone.restapi/issues/298 https://github.com/plone/plone.restapi/pull/297

This release might contain breaking changes!

Planned: May 2017

**plone.restapi 1.0aXXX**

- [ ] Error handling is inconsistent and undocumented: https://github.com/plone/plone.restapi/issues/165
- [x] 100% code coverage: https://github.com/plone/plone.restapi/issues/287 
- [ ] Object Serializer/Deserializer: https://github.com/plone/plone.restapi/pull/177
- [ ] Content Rules: https://github.com/plone/plone.restapi/issues/324

Planned: May 2017

**plone.restapi beta release**

- [ ] Use plone.api in plone.restapi: https://github.com/plone/plone.restapi/issues/234 
- [ ] ... TODO!

No breaking API changes in beta.

Planned: Mid 2017

**plone.restapi release candidate**

- [ ] Documentation overhaul: ...
- [ ] Browsable API: https://github.com/plone/plone.restapi/issues/161
- [ ] API Specification / Guillotina API sync:

Planned: 2017

**Comment by tisto** [comment]
Closing this issue. We are close to release 1.0b1 and 1.0 final.
